# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - run: npm i
      - run: npm i -g @angular/cli

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      #- run: git branch --track main origin/main

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
